server:
  port: 8763

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        default_schema: auth
        jdbc:
          lob.non_contextual_creation: true
  flyway:
    baseline-on-migrate: true
    schemas: auth

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug
